### ISSUE TITLE
Uncaught Exception on Startup

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-nano#364]
I have the following error in the console on Startup, when I say "No" to install it in the system. But Nano seems to run fine anyways:
```
Uncaught Exception:
TypeError: app.setAboutPanelOptions is not a function
    at Object.<anonymous> (/tmp/.mount_XNnZ9z/usr/bin/resources/app.asar/main.js:188:5)
    at Object.<anonymous> (/tmp/.mount_XNnZ9z/usr/bin/resources/app.asar/main.js:199:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/tmp/.mount_XNnZ9z/usr/bin/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/tmp/.mount_XNnZ9z/usr/bin/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
```

**Comment by Isabello** [comment]
Please report system information including Kernel, Linux distro etc.

**Comment by simonmorgenthaler** [comment]
Linux 3.19.0-32-generic #37~14.04.1-Ubuntu SMP x86_64 GNU/Linux
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"

**Comment by Isabello** [comment]
Thank you :)
