### ISSUE TITLE
Upgrade cucumber and protractor-cucumber-framework

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#794]
### Expected behaviour
There are newer versions of `cucumber` and `protractor-cucumber-framework`:
```
"cucumber": "3.0.3",
"protractor-cucumber-framework": "4.0.8",
```
We should use them, but there is some error, so it needs some investigation and a fix.
Afterwards, this commit should be reverted to remove the two dependencies from greenkeeper ignore list:
https://github.com/LiskHQ/lisk-nano/pull/776/commits/96f931d33165a3aef100131b6cf617be98733e82
### Actual behaviour
Using the new versions causes the following error
```
$ npm run e2e-test -s
(node:83681) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[10:56:48] I/launcher - Running 1 instances of WebDriver
[10:56:48] I/direct - Using ChromeDriver directly...
Unhandled rejection Error: Cannot find module '/Users/slaweet/git/nano-greenkeeper/pretty'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.loadCustomFormatter (/Users/slaweet/git/nano-greenkeeper/node_modules/cucumber/src/formatter/builder.js:73:29)
    at Function.getConstructorByType (/Users/slaweet/git/nano-greenkeeper/node_modules/cucumber/src/formatter/builder.js:47:33)
    at Function.build (/Users/slaweet/git/nano-greenkeeper/node_modules/cucumber/src/formatter/builder.js:17:40)
    at /Users/slaweet/git/nano-greenkeeper/node_modules/cucumber/src/cli/index.js:50:31
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/slaweet/git/nano-greenkeeper/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/slaweet/git/nano-greenkeeper/node_modules/bluebird/js/release/generators.js:97:49)
    at /Users/slaweet/git/nano-greenkeeper/node_modules/bluebird/js/release/generators.js:201:15
    at /Users/slaweet/git/nano-greenkeeper/node_modules/cucumber/src/cli/index.js:35:11
    at tryCatcher (/Users/slaweet/git/nano-greenkeeper/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/slaweet/git/nano-greenkeeper/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/slaweet/git/nano-greenkeeper/node_modules/bluebird/js/release/promise_array.js:114:31)
```

**Comment by NomiJ** [comment]
We are facing the same problem, is there any fix for this?
    "cucumber": "3.2.0",
    "protractor": "5.1.2",
    "protractor-cucumber-framework": "4.1.1",

**Comment by slaweet** [comment]
@NomiJ I was playing with it a bit some time ago and I could fix the error `Cannot find module '/Users/slaweet/git/nano-greenkeeper/pretty'`, which happens because `pretty` formatter was removed, removing this line fixes it:
https://github.com/LiskHQ/lisk-nano/blob/475707bc76a6b123008741b5175b7c29b4d94b22/protractor.conf.js#L18

But there was some other error afterward that I couldn't fix.
